#!/usr/bin/env bash
#multipliers

for x in {1..100}
do
    if
	(( 15 % x == 0 ))
    then
	echo "FizzBuzz"
	elif
	    (( x % 3 == 0 ))
	then
	    echo "Fizz"
	    elif
		(( x % 5 == 0 ))
	    then
		echo "Buzz"
	    else
		echo "$x"
		fi
done
