#!/usr/bin/env bash
#schoolfile
FILE=school
if
    [ -e "$FILE" ];
then
    echo "$FILE file exists"
else 
    echo "$FILE file does not exist"
    fi
    if
	[ -s $FILE ];
    then
	echo "$FILE school file is not empty"
    else
	echo "$FILE school file is empty"
    fi
    if
	[ -f "$FILE" ];
    then
	echo "$FILE school is a regular file"
    else
	echo "$FILE"
	fi
