#!/usr/bin/env bash
#schoolfile
if
    [ -e ./school ]
then
    echo "file exists"
       
    if
	[ -s ./school ]
    then
	echo "school file is not empty"
    else
	echo "school file is empty"
    fi
    if
	[ -f ./school ]
    then
	echo "school is a regular fil"
    fi
else
echo "school file does not exist"
fi
